In [2]:
import numpy as np

In [3]:
import numpy as np
print(np.__version__)


arr = np.array([1, 2, 3, 4, 5])

2.0.2


In [4]:
a = [1, 2, 3, 4]
print(a+a+a)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [5]:
a = np.array([1, 2, 3, 4])
print(a+a+a)


[ 3  6  9 12]


In [6]:
arr = np.array([1, 2, 3])
print(arr[1]*2)

4


In [7]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
random_arr = np.random.rand(2, 2)
print(random_arr)

[[0.3332078  0.19718919]
 [0.16481843 0.63302112]]


In [9]:
seq = np.arange(0, 10, 2)
print(seq)

[0 2 4 6 8]


In [ ]:
lin = np.linspace(0, 1, 11)
print(lin)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [10]:
arr = np.array([10, 20, 30, 40])
print(arr[0])



10


In [11]:
print(arr[-1],arr[3])

40 40
